### ISSUE TITLE
some sort of more precise progress indicator

### ISSUE THREAD

**Issue by walksanatora** [acikek/the-printer#3]
it would be nice to have a Percent or progress bar as that would make seeing its progress easier to understand (doubly so for transparent items)
even if it is just a JADE/WTHIT integration i would be happy

**Comment by walksanatora** [comment]
+redstone would also be a nice milestone, use a repeater, 0-13 is how "full" it is, 14 is crafting, 15 is done

**Comment by acikek** [comment]
Added WTHIT integration in 5bca895 and the comparator support in b7b16e9. Will be in the next update.
