### ISSUE TITLE
[feature] Creating a config file to edit xp prices easier

### ISSUE THREAD

**Issue by IIVIIVII** [acikek/the-printer#5]
Would it be possible to make it that the mod creates an .cfg file in the config folder for easier configuration of the mod?

Thank you for reading in advance. Have a great day

**Comment by acikek** [comment]
Implementing [Printer Rules](https://github.com/acikek/the-printer/wiki/Printer-Rules) in the config would yield diminishing returns. Just create a datapack, possibly utilizing a global datapacks mod [such as this one](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack).
