### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [acikek/the-printer#8]
The sodium mode printer mode has a mismatch with the transparency and the game crashes. This problem was also experienced in previous versions, now this situation is available in 1.20.1.
[latest.log](https://github.com/acikek/the-printer/files/11870759/latest.log)
[crash-2023-06-26_18.01.31-client.txt](https://github.com/acikek/the-printer/files/11870762/crash-2023-06-26_18.01.31-client.txt)

**Comment by acikek** [comment]
Whoops, I was messing around with the Sodium API and I forgot to undo my changes for the release. I'll get it fixed today.

**Comment by acikek** [comment]
Should be fine now? Released a hotfix version

**Comment by Rogenar** [comment]
yes the problem is fixed. I have a small request idea that I want to share with you. If the percentage (%) indicator is added on the item while it is being copied, we can see when the item will be copied.

**Comment by acikek** [comment]
I think there's an arrow when it's printing already? Anyways, in the future please create separate issues for requests
